services:
  project_backend:
    build: .
    container_name: back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=budeikin
      - POSTGRES_PASSWORD=13906060a
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  smtp4dev:
    container_name: email_sender
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  db:
  smtp4dev-data: