# Generated by Django 3.2 on 2023-09-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20230927_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
