# Generated by Django 3.2 on 2023-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_app', '0005_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('date_of_birth', models.PositiveIntegerField()),
                ('date_of_death', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
