# Generated by Django 3.2 on 2023-09-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
