# Generated by Django 3.2 on 2023-09-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_author_date_of_death'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
