# Generated by Django 3.2 on 2023-10-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20231001_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='writers/'),
        ),
    ]
