# Generated by Django 3.2 on 2023-10-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_writer_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='cover',
            new_name='image',
        ),
    ]
