# Generated by Django 3.2 on 2023-10-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
