# Generated by Django 3.2 on 2023-10-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
